let questions = [

    {
        title:"1 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"2 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"3 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"4 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"5 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"6 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"7 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"8 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"9 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"10 In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
    {
        title:"In a region of constant potential ?",
        answers: ["there can be no charge inside the region.",
        "the electric field is uniform.",
        "the electric field is zero.",
        "both (a) and (c) are correct."],
        correctAnswer : "both (a) and (c) are correct.",
    },
];